const DATA = [
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "No",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "3+ years (e.g. degree)",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Full stack software engineer",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": 2,
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP), Security (e.g. NSE)",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Cloud engineer",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "GoLang, Bash / Shell / Powershell, Ruby"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "No",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Back end software engineer",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": "3+",
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP)",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "DevOps",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "Python, Bash / Shell / Powershell, PHP"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "No",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Manager",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 1,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "Networking (e.g. CCNA)",
        "If your current job is cloud related, how many certifications do you hold?": "3+",
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Networking (e.g. CCNA), Security (e.g. NSE), CISM",
        "If your current job is related to cloud, do you write software / code?": "No",
        "If your current job is within cloud, which of the following job titles could apply to you?": "N/A",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "N/A"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "Yes",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "6-12 months (e.g. part-time bootcamp)",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Full stack software engineer",
        "What is your education background?": "Master's degree (engineering)",
        "How many certifications did you hold when you got your first tech job?": 1,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "Networking (e.g. CCNA)",
        "If your current job is cloud related, how many certifications do you hold?": "N/A",
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "N/A",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "N/A",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "Bash / Shell / Powershell, Terraform"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "Yes",
        "Do you have a professional background related to on-premise infrastructure?": "Yes",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "3-6 months (e.g. intensive bootcamp)",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "N/A",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": "3+",
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP)",
        "If your current job is cloud related, how many certifications do you hold?": "3+",
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP)",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Cloud engineer",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "JavaScript, Python, Bash / Shell / Powershell"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "Yes",
        "Do you have a professional background related to on-premise infrastructure?": "Yes",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Front end software engineer",
        "What is your education background?": "Bootcamp graduate",
        "How many certifications did you hold when you got your first tech job?": 1,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": 0,
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "N/A",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Full stack software engineer",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "JavaScript, Python"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "Yes",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Analyst / Consultant, Security Consultant",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": 2,
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP), Security (e.g. NSE)",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Analyst / Consultant, Security Consultant",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "Python, GoLang, Bash / Shell / Powershell"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "Yes",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "1-2 years",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Full stack software engineer",
        "What is your education background?": "Self taught since I was 12 + BSc degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": 2,
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP)",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Back end software engineer, DevOps, Cloud engineer",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "JavaScript, Python, Bash / Shell / Powershell, C#"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "Yes",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Manager, Sys / DB Admin",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": 0,
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "N/A",
        "If your current job is related to cloud, do you write software / code?": "No",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Sys or DB Admin, DevOps, Cloud engineer",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "Bash / Shell / Powershell"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "No",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Support",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": "N/A",
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "N/A",
        "If your current job is related to cloud, do you write software / code?": "No",
        "If your current job is within cloud, which of the following job titles could apply to you?": "N/A",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "N/A"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "Yes",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Support, Network Back-Office Support",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 1,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "Networking (e.g. CCNA)",
        "If your current job is cloud related, how many certifications do you hold?": "N/A",
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "N/A",
        "If your current job is related to cloud, do you write software / code?": "N/A",
        "If your current job is within cloud, which of the following job titles could apply to you?": "N/A",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "N/A"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "No",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Full stack software engineer",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": 2,
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP)",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Manager (i.e Engineering manager / Delivery manager), Analyst / Consultant, DevOps, Cloud engineer",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "JavaScript, Python, Bash / Shell / Powershell, .net"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "Yes",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Sys / DB Admin",
        "What is your education background?": "Self-taught",
        "How many certifications did you hold when you got your first tech job?": 1,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "MCP",
        "If your current job is cloud related, how many certifications do you hold?": "3+",
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP), Security (e.g. NSE)",
        "If your current job is related to cloud, do you write software / code?": "No",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Domain Architect",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "N/A"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "Yes",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "0-3 months (e.g. self-taught or short course)",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Support",
        "What is your education background?": "N/A",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": 1,
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP)",
        "If your current job is related to cloud, do you write software / code?": "No",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Support (e.g. IT, ops)",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "N/A"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "Yes",
        "Do you have a professional background related to on-premise infrastructure?": "No",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "0-3 months (e.g. self-taught or short course)",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Business Analyst",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP)",
        "If your current job is cloud related, how many certifications do you hold?": 1,
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP)",
        "If your current job is related to cloud, do you write software / code?": "N/A",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Analyst / Consultant, Cloud engineer",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "N/A"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "No",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "0-3 months (e.g. self-taught or short course)",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Analyst / Consultant",
        "What is your education background?": "Self-taught",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": 0,
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "N/A",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "DevOps, Support (e.g. IT, ops)",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "JavaScript, GoLang, Bash / Shell / Powershell"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "No",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Network protocols for embedded systems",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": 0,
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "N/A",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Sys or DB Admin, DevOps, Cloud engineer, Support (e.g. IT, ops)",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "Python, Bash / Shell / Powershell, PHP"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "No",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Quality Assurance (testing)",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": "N/A",
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "N/A",
        "If your current job is related to cloud, do you write software / code?": "No",
        "If your current job is within cloud, which of the following job titles could apply to you?": "N/A",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "N/A"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "Yes",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Sys / DB Admin",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": "N/A",
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": "3+",
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP)",
        "If your current job is related to cloud, do you write software / code?": "No",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Cloud engineer",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "Bash / Shell / Powershell"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "Yes",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Sys / DB Admin",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": "N/A",
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": "3+",
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP)",
        "If your current job is related to cloud, do you write software / code?": "No",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Cloud engineer",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "Bash / Shell / Powershell"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "Yes",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Sys / DB Admin",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": 0,
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "N/A",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Sys or DB Admin, DevOps, Cloud engineer",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "Python, Bash / Shell / Powershell"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "No",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "0-3 months (e.g. self-taught or short course)",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Back end software engineer",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": 2,
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP), java certs",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Full stack software engineer, Cloud engineer",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "JavaScript, Python, Bash / Shell / Powershell"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "Yes",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Analyst / Consultant",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": 1,
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP)",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Cloud engineer",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "JavaScript, Bash / Shell / Powershell, PHP"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "No",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Back end software engineer",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": 0,
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "N/A",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Full stack software engineer, Analyst / Consultant, Support (e.g. IT, ops)",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "Java"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "Yes",
        "Do you have a professional background related to on-premise infrastructure?": "Yes",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "0-3 months (e.g. self-taught or short course)",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "N/A",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": 1,
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP)",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Cloud engineer",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "Python"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "No",
        "Do you have a professional background related to on-premise infrastructure?": "No",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "N/A",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "Back end software engineer",
        "What is your education background?": "Formal Degree",
        "How many certifications did you hold when you got your first tech job?": 0,
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "N/A",
        "If your current job is cloud related, how many certifications do you hold?": "3+",
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP), TOGAF, ITIL",
        "If your current job is related to cloud, do you write software / code?": "Yes",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Manager (i.e Engineering manager / Delivery manager)",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "Python, Bash / Shell / Powershell"
    },
    {
        "Do you work in tech?": "Yes",
        "Was your first job in tech related to cloud?": "Yes",
        "Do you have a professional background related to on-premise infrastructure?": "No",
        "If your first tech job was related to cloud, how long did you spend preparing/learning for your first job?": "1-2 years",
        "If your first job in tech wasn't cloud related, which of the following job titles could describe your first job?": "N/A",
        "What is your education background?": "Self-taught",
        "How many certifications did you hold when you got your first tech job?": "3+",
        "When you got your first tech job if you had 1 or more certifications, what were those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP)",
        "If your current job is cloud related, how many certifications do you hold?": "3+",
        "If your current job is cloud related and you hold 1 or more certifications, what are those certifications?": "Cloud certifications (e.g. AWS/Azure/GCP)",
        "If your current job is related to cloud, do you write software / code?": "No",
        "If your current job is within cloud, which of the following job titles could apply to you?": "Training Architect- create content",
        "If you work in cloud, what programming languages have you used in the last ~3 months?": "Python"
    }
]
